name: First Workflow
on: [push] # events

jobs:
  run-shell-comands:  # id job 1  
    runs-on: ubuntu-latest # machine
    steps: #steps of first job
      - name: echo a string
        run: echo "hello world"
      - name: multiline command
        run: | # more than one step
          node -v
          npm -v